/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {},
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        barracuda: {
          "primary": "#FF6B6B",
          "primary-focus": "#FF5252",
          "primary-content": "#FFFFFF",
          "secondary": "#6B7280",
          "secondary-focus": "#4B5563",
          "secondary-content": "#FFFFFF",
          "accent": "#FF6B6B",
          "accent-focus": "#FF5252",
          "accent-content": "#FFFFFF",
          "neutral": "#282828",
          "neutral-focus": "#1F1F1F",
          "neutral-content": "#FFFFFF",
          "base-100": "#282828",
          "base-200": "#1F1F1F",
          "base-300": "#171717",
          "base-content": "#FFFFFF",
          "info": "#3B82F6",
          "info-content": "#FFFFFF",
          "success": "#15803d",
          "success-content": "#FFFFFF",
          "warning": "#F59E0B",
          "warning-content": "#FFFFFF",
          "error": "#b91c1c",
          "error-content": "#FFFFFF",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
        },
      },
    ],
  },
}

